### ISSUE TITLE
Enemies können noch im gleichen Raum sein 

### ISSUE THREAD

**Issue by LucasEAB** [LucasEAB/WS1920_SWD#1]
Das Problem ist das Enemies noch in dem selben Raum durch den Random Move kommen. Des weiteren bleiben diese dann immer im selben Raum und nur einer der Enemies wird in der Ausgabe ausgegeben und man kann nur mit diesem interagieren. 

Wenn man eine Richtung eingibt, wird eine Random-Nummer erzeugt, die die Richtung bestimmt in welche sich der Enemy bewegen soll: 

https://github.com/LucasEAB/WS1920_SWD/blob/a8c97688ed7b8d16c4c297e90568344d9c03fb4d/TextAdventure/Game.cs#L155-L186

Hierfür wäre eine vermutliche Lösung abzufragen, dass in RoomPlayers in der Klasse Room kein Enemy in der Liste vorhanden ist: 

https://github.com/LucasEAB/WS1920_SWD/blob/a8c97688ed7b8d16c4c297e90568344d9c03fb4d/TextAdventure/Room.cs#L10

Ich habe versucht, diese Liste von der Klasse Game aus aufzurufen, allerdings bekomme ich die Meldung "The name 'RoomPlayers' does not exist in the current context".

**Comment by JirkaDellOro** [comment]
Das ist alles recht unklar und der Code widerspricht auch einigen wichtigen Gestaltungsregeln. Wir solten Skypen, morgen früh um 8.30 Uhr, mein Nutzername ist entertrain.

**Comment by LucasEAB** [comment]
Okay ich werde Sie dann morgen über Skype anrufen
